### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by jeremyTyriaux** [martianov/typed-save-svg-as-png#1]
Hello, 
i use the typings install save-svg-as-png command. But after, how can i use it in my Typescript project ?

thanks.

**Comment by maaqoul** [comment]
did you figure out how to use it ??

**Comment by martianov** [comment]
Guys, as Typings are

**Comment by martianov** [comment]
Guys, since Typings registry are deprecated since TypeScript@2.0 this repository is no longer relevant.
Consider using another typings (https://github.com/CinnamonRage/types-save-svg-as-png) please.
