### ISSUE TITLE
@types on npm

### ISSUE THREAD

**Issue by devwolf75** [martianov/typed-save-svg-as-png#3]
I have been looking for this types in npm and couldn't find them. @types is the default for Angular.

**Comment by ciriousjoker** [comment]
Same here, @types is the goto typing definitions not only for Angular but for every npm package that doesn't provide its own typings.

**Comment by martianov** [comment]
Some good guys created definitions in @types registry: https://github.com/CinnamonRage/types-save-svg-as-png
This repo is no longer relevant.
